/* Generated By:JJTree: Do not edit this line. ASTColumnAlias.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTColumnAlias extends SimpleNode {
  public ASTColumnAlias(int id) {
    super(id);
  }

  public ASTColumnAlias(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad1a1693fd4332099fe7746d7dec8d90 (do not edit this line) */
