/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIDENTIFIER extends SimpleNode {
  public ASTIDENTIFIER(int id) {
    super(id);
  }

  public ASTIDENTIFIER(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a3d0f66087033ca170fc280966a575d (do not edit this line) */
