/* Generated By:JJTree: Do not edit this line. ASTNumericLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumericLiteral extends SimpleNode {
  public ASTNumericLiteral(int id) {
    super(id);
  }

  public ASTNumericLiteral(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d03e5bfff9da76725bccc0944ea9d75c (do not edit this line) */
