/* Generated By:JJTree: Do not edit this line. ASTResultColumn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTResultColumn extends SimpleNode {
  public ASTResultColumn(int id) {
    super(id);
  }

  public ASTResultColumn(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d1d4a88c470238ba36d77d2e3306a68 (do not edit this line) */
