/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 7.0.10 */
public interface SQLParserTreeConstants
{
  public int JJTTABLENAME = 0;
  public int JJTTABLEALIAS = 1;
  public int JJTCOLUMNNAME = 2;
  public int JJTCOLUMNALIAS = 3;
  public int JJTFUNCTIONNAME = 4;
  public int JJTSTRINGLITERAL = 5;
  public int JJTNUMERICLITERAL = 6;
  public int JJTLITERALVALUE = 7;
  public int JJTORDERTERM = 8;
  public int JJTSTART = 9;
  public int JJTEXPRESSION = 10;
  public int JJTSELECTSTMT = 11;
  public int JJTARITHMETICOPERATOR = 12;
  public int JJTLOGICALOPERATOR = 13;
  public int JJTCOMPARISONOPERATOR = 14;
  public int JJTOPERATOR = 15;
  public int JJTRESULTCOLUMN = 16;
  public int JJTEXPR = 17;
  public int JJTEXPRR = 18;
  public int JJTFROMLIST = 19;
  public int JJTTUPLE = 20;
  public int JJTCRET = 21;
  public int JJTCOLLIST = 22;
  public int JJTTYPE = 23;
  public int JJTDROPT = 24;
  public int JJTDELT = 25;
  public int JJTDELLIST = 26;
  public int JJTINST = 27;
  public int JJTINLIST = 28;
  public int JJTVLIST = 29;
  public int JJTATTRIBUTE = 30;
  public int JJTRELATION = 31;
  public int JJTPATTERN = 32;
  public int JJTIDENTIFIER = 33;


  public String[] jjtNodeName = {
    "TableName",
    "TableAlias",
    "ColumnName",
    "ColumnAlias",
    "FunctionName",
    "StringLiteral",
    "NumericLiteral",
    "LiteralValue",
    "OrderTerm",
    "Start",
    "Expression",
    "SelectStmt",
    "ArithmeticOperator",
    "LogicalOperator",
    "ComparisonOperator",
    "Operator",
    "ResultColumn",
    "Expr",
    "Exprr",
    "FromList",
    "Tuple",
    "CreT",
    "ColList",
    "Type",
    "DropT",
    "DelT",
    "DelList",
    "InsT",
    "InList",
    "VList",
    "Attribute",
    "Relation",
    "Pattern",
    "IDENTIFIER",
  };
}
/* JavaCC - OriginalChecksum=fdd19d0ab1991268d9547719e30b2f2a (do not edit this line) */
