/* Generated By:JJTree&JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int DROP = 7;
  /** RegularExpression Id. */
  int DELETE = 8;
  /** RegularExpression Id. */
  int SELECT = 9;
  /** RegularExpression Id. */
  int INSERT = 10;
  /** RegularExpression Id. */
  int WHERE = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int INTO = 13;
  /** RegularExpression Id. */
  int DISTINCT = 14;
  /** RegularExpression Id. */
  int ALL = 15;
  /** RegularExpression Id. */
  int LIKE = 16;
  /** RegularExpression Id. */
  int ORDER = 17;
  /** RegularExpression Id. */
  int BY = 18;
  /** RegularExpression Id. */
  int AS = 19;
  /** RegularExpression Id. */
  int VALUES = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int CHAR = 24;
  /** RegularExpression Id. */
  int DATE = 25;
  /** RegularExpression Id. */
  int IS = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int ISNULL = 28;
  /** RegularExpression Id. */
  int NOTNULL = 29;
  /** RegularExpression Id. */
  int NULL = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int BETWEEN = 32;
  /** RegularExpression Id. */
  int GROUP = 33;
  /** RegularExpression Id. */
  int HAVING = 34;
  /** RegularExpression Id. */
  int LIMIT = 35;
  /** RegularExpression Id. */
  int OFFSET = 36;
  /** RegularExpression Id. */
  int ASC = 37;
  /** RegularExpression Id. */
  int DESC = 38;
  /** RegularExpression Id. */
  int LAST = 39;
  /** RegularExpression Id. */
  int FIRST = 40;
  /** RegularExpression Id. */
  int NULLS = 41;
  /** RegularExpression Id. */
  int UNDERSCORE = 42;
  /** RegularExpression Id. */
  int COMMA = 43;
  /** RegularExpression Id. */
  int SEMICOLON = 44;
  /** RegularExpression Id. */
  int COLON = 45;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 46;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 47;
  /** RegularExpression Id. */
  int EQUAL = 48;
  /** RegularExpression Id. */
  int PLUS = 49;
  /** RegularExpression Id. */
  int MINUS = 50;
  /** RegularExpression Id. */
  int TIMES = 51;
  /** RegularExpression Id. */
  int DIVIDE = 52;
  /** RegularExpression Id. */
  int DOT = 53;
  /** RegularExpression Id. */
  int GREATERTHAN = 54;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 55;
  /** RegularExpression Id. */
  int LESSTHAN = 56;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 57;
  /** RegularExpression Id. */
  int LEFTQUOTATION = 58;
  /** RegularExpression Id. */
  int LQUOTATION = 59;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 60;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 61;
  /** RegularExpression Id. */
  int DIGIT = 62;
  /** RegularExpression Id. */
  int IDENTIFIER = 63;
  /** RegularExpression Id. */
  int LETTER = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"create\"",
    "\"table\"",
    "\"drop\"",
    "\"delete\"",
    "\"select\"",
    "\"insert\"",
    "\"where\"",
    "\"from\"",
    "\"into\"",
    "\"distinct\"",
    "\"all\"",
    "\"like\"",
    "\"order\"",
    "\"by\"",
    "\"as\"",
    "\"values\"",
    "\"and\"",
    "\"in\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"is\"",
    "\"not\"",
    "\"ISNULL\"",
    "\"NOTNULL\"",
    "\"null\"",
    "\"or\"",
    "\"between\"",
    "\"group\"",
    "\"having\"",
    "\"limit\"",
    "\"offset\"",
    "\"asc\"",
    "\"desc\"",
    "\"last\"",
    "\"first\"",
    "\"nulls\"",
    "\"_\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\".\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
