/* Generated By:JavaCC: Do not edit this line. SQLParserDefaultVisitor.java Version 7.0.10 */
public class SQLParserDefaultVisitor implements SQLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableAlias node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnAlias node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStringLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumericLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLiteralValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOrderTerm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSelectStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArithmeticOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogicalOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparisonOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTResultColumn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExprr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFromList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTuple node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCreT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDropT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDelT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDelList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInsT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAttribute node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelation node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPattern node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDENTIFIER node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=3cccfa9627e535683c64d99b4f6d4913 (do not edit this line) */
