/* Generated By:JJTree: Do not edit this line. ASTConstraint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

import java.io.Serializable;

@Data
public class ASTConstraint extends SimpleNode implements Serializable {
    private Integer type;
    private ASTTableName tableName;
    private ASTColumnName foreignKeyColumn;
    private ASTColumnName columnName;
    private ASTColumnList columnList;
    public ASTConstraint(int id) {
        super(id);
    }

    public ASTConstraint(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=71b7a56d52795aeb55cb8b4713d9a5ab (do not edit this line) */
