/* Generated By:JJTree: Do not edit this line. ASTData.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ASTData extends SimpleNode {
    private ASTNumericLiteral numericLiteral = null;
    private ASTStringLiteral stringLiteral = null;

    public ASTData(int id) {
        super(id);
    }

    public ASTData(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public int getType() {
        if (numericLiteral != null) return numericLiteral.getType();
        else if (stringLiteral != null) return 3;
        else return -1;
    }

    public String getValue() {
        if (numericLiteral != null) {
            return numericLiteral.getValue();
        } else if (stringLiteral != null) {
            return stringLiteral.getValue();
        } else {
            return null;
        }
    }
}
/* JavaCC - OriginalChecksum=61a79300656f200a0d862a65876e3386 (do not edit this line) */
