/* Generated By:JJTree: Do not edit this line. ASTFromTable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

@Data
public class ASTFromTable extends SimpleNode {
  private ASTTableName tableName;
  private Boolean havaAlias;
  private String alias;
  public ASTFromTable(int id) {
    super(id);
  }

  public ASTFromTable(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7939733e0a09927fef9dfeb1dc6c50ae (do not edit this line) */
