/* Generated By:JJTree: Do not edit this line. ASTFromList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class ASTFromList extends SimpleNode {
    private List<ASTFromTable> fromTables = new ArrayList<>();

    public ASTFromList(int id) {
        super(id);
    }

    public ASTFromList(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=8b6c10fd836c45b19b6258ccf87bc310 (do not edit this line) */
