/* Generated By:JJTree: Do not edit this line. ASTFieldConstraint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

public class ASTFieldConstraint extends ASTConstraint {
  public ASTFieldConstraint(int id) {
    super(id);
  }

  public ASTFieldConstraint(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ff03e7af458c705688c3da56e0abdef (do not edit this line) */
