/* Generated By:JJTree: Do not edit this line. ASTInsertStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

@Data
public class ASTInsertStmt extends SimpleNode {
    private ASTTableName tableName;
    private ASTColumnList columnList;
    private ASTValueList valueList;

    public ASTInsertStmt(int id) {
        super(id);
    }

    public ASTInsertStmt(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=bb0344ada4b43fc1789403be45fef712 (do not edit this line) */
