/* Generated By:JJTree: Do not edit this line. ASTLimit.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

@Data
public class ASTLimit extends SimpleNode {
  private Integer limit;
  private Integer offset;
  public ASTLimit(int id) {
    super(id);
  }

  public ASTLimit(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c58d440e258cb49ab159e128b5c2d33 (do not edit this line) */
