/* Generated By:JJTree: Do not edit this line. ASTLiteralValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

public
class ASTLiteralValue extends SimpleNode {
  public ASTLiteralValue(int id) {
    super(id);
  }

  public ASTLiteralValue(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=146ca91f44f0c8dde8dc20cdf3ee8a2f (do not edit this line) */
