/* Generated By:JJTree: Do not edit this line. ASTNullExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import com.yjq.parser.interfaces.Expression;
import lombok.Data;

@Data
public class ASTNullExpression extends SimpleNode implements Expression {
    private ASTColumnName columnName = null;
    private boolean isNull = false;
    private boolean is = false;
    private boolean not = false;
    private boolean nulls = false;

    public ASTNullExpression(int id) {
        super(id);
    }

    public ASTNullExpression(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }

    @Override
    public boolean result() {
        if (isNull) {
            return columnName.getData() == null || "".equals(columnName.getData().getValue());
        } else {
            if (not) {
                if(columnName.getData() ==null){
                    return false;
                }else {
                    return !"".equals(columnName.getData().getValue());
                }
            } else {
                return columnName.getData() == null || "".equals(columnName.getData().getValue());
            }
        }
    }
}
/* JavaCC - OriginalChecksum=8c8d5646d72ac1c48e68bf76124c52df (do not edit this line) */
