/* Generated By:JJTree: Do not edit this line. ASTOrderBy.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

public
class ASTOrderBy extends SimpleNode {
  public ASTOrderBy(int id) {
    super(id);
  }

  public ASTOrderBy(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cfac3f6d05ad022425707cfb2f9f5588 (do not edit this line) */
