/* Generated By:JJTree: Do not edit this line. ASTResultColumn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.lang.ref.PhantomReference;

@Data
public class ASTResultColumn extends SimpleNode {
    private String childName;
    private Integer type;
    private ASTTableName tableName;
    private ASTColumnName columnName;
    private ASTFunction function;
    private Boolean haveAlias = false;
    private String alias;

    public ASTResultColumn(int id) {
        super(id);
    }

    public ASTResultColumn(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String getAlias() {
        if (haveAlias) {
            return alias;
        } else {
            return getNameWithTable();
        }
    }

    public String getNameWithTable() {
        return columnName.getNameWithTable();
    }
}
/* JavaCC - OriginalChecksum=7f5bab010b7d8e2aa3b06bd5a98d572a (do not edit this line) */
