/* Generated By:JJTree: Do not edit this line. ASTTableConstraints.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

public class ASTTableConstraints extends ASTConstraints {
  public ASTTableConstraints(int id) {
    super(id);
  }

  public ASTTableConstraints(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f2960b4b004d294e0cf3b93eadf1ad63 (do not edit this line) */
