/* Generated By:JJTree: Do not edit this line. ASTTableAlias.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

public
class ASTTableAlias extends SimpleNode {
  public ASTTableAlias(int id) {
    super(id);
  }

  public ASTTableAlias(SQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c359eedb30ddb6f87050d8a6b04f9ced (do not edit this line) */
