/* Generated By:JJTree: Do not edit this line. ASTUpdateStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

@Data
public class ASTUpdateStmt extends SimpleNode {
    private ASTTableName tableName;
    private ASTSetList setList;
    private ASTExpression expression;

    public ASTUpdateStmt(int id) {
        super(id);
    }

    public ASTUpdateStmt(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=da2c2c07eb51d2f81101afbf7a20dabc (do not edit this line) */
