/* Generated By:JJTree: Do not edit this line. ASTUpdateValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

@Data
public class ASTUpdateValue extends SimpleNode {
    private ASTColumnName columnName;
    private ASTData data;

    public ASTUpdateValue(int id) {
        super(id);
    }

    public ASTUpdateValue(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=e3534f44fb8a04db4653e52eb01262fb (do not edit this line) */
