/* Generated By:JJTree: Do not edit this line. ASTValueList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class ASTValueList extends SimpleNode {
    private List<ASTValue> values = new ArrayList<>();

    public ASTValueList(int id) {
        super(id);
    }

    public ASTValueList(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=f8cabf738041672364db68c5d9366434 (do not edit this line) */
