/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.yjq.parser.jjt;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ASTValue extends SimpleNode {
    private ASTData data = null;
    private ASTColumnName columnName = null;

    public ASTValue(int id) {
        super(id);
    }

    public ASTValue(SQLParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(SQLParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }

    /**
     * 获取value类型
     *
     * @return
     */
    public int getType() {
        if (data != null) return data.getType();
        else if (columnName != null) return 4;
        else return -1;
    }

    public String getValue() {
        if (data != null) {
            return data.getValue();
        } else if (columnName != null) {
            return columnName.getData().getValue();
        }
        return null;
    }
}
/* JavaCC - OriginalChecksum=ad521dae29a735fffc871a92d21c339d (do not edit this line) */
