/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 7.0.10 */
package com.yjq.parser.jjt;

public interface SQLParserTreeConstants
{
  public int JJTTABLENAME = 0;
  public int JJTCOLUMNNAME = 1;
  public int JJTFUNCTION = 2;
  public int JJTSTRINGLITERAL = 3;
  public int JJTNUMERICLITERAL = 4;
  public int JJTLITERALVALUE = 5;
  public int JJTSTART = 6;
  public int JJTSTATEMENT = 7;
  public int JJTSELECTSTMT = 8;
  public int JJTARITHMETICOPERATOR = 9;
  public int JJTLOGICALOPERATOR = 10;
  public int JJTCOMPARISONOPERATOR = 11;
  public int JJTANDEXPRESSION = 12;
  public int JJTOREXPRESSION = 13;
  public int JJTNULLEXPRESSION = 14;
  public int JJTLIKEEXPRESSION = 15;
  public int JJTINEXPRESSION = 16;
  public int JJTBETWEENEXPRESSION = 17;
  public int JJTCOMPARISONEXPRESSION = 18;
  public int JJTDATA = 19;
  public int JJTVALUE = 20;
  public int JJTEXPRESSION = 21;
  public int JJTCONDITION = 22;
  public int JJTORDERBY = 23;
  public int JJTGROUPBY = 24;
  public int JJTLIMIT = 25;
  public int JJTEXIST = 26;
  public int JJTOPERATOR = 27;
  public int JJTRESULT = 28;
  public int JJTRESULTCOLUMN = 29;
  public int JJTFROMLIST = 30;
  public int JJTFROMTABLE = 31;
  public int JJTTUPLE = 32;
  public int JJTCREATESTMT = 33;
  public int JJTCOLLIST = 34;
  public int JJTFIELD = 35;
  public int JJTCONSTRAINTS = 36;
  public int JJTCONSTRAINT = 37;
  public int JJTDROPT = 38;
  public int JJTDELETESTMT = 39;
  public int JJTUPDATESTMT = 40;
  public int JJTSETLIST = 41;
  public int JJTUPDATEVALUE = 42;
  public int JJTINSERTSTMT = 43;
  public int JJTCOLUMNLIST = 44;
  public int JJTDATALIST = 45;
  public int JJTATTRIBUTE = 46;
  public int JJTRELATION = 47;
  public int JJTPATTERN = 48;
  public int JJTIDENTIFIER = 49;


  public String[] jjtNodeName = {
    "TableName",
    "ColumnName",
    "Function",
    "StringLiteral",
    "NumericLiteral",
    "LiteralValue",
    "Start",
    "Statement",
    "SelectStmt",
    "ArithmeticOperator",
    "LogicalOperator",
    "ComparisonOperator",
    "AndExpression",
    "OrExpression",
    "NullExpression",
    "LikeExpression",
    "InExpression",
    "BetweenExpression",
    "ComparisonExpression",
    "Data",
    "Value",
    "Expression",
    "Condition",
    "OrderBy",
    "GroupBy",
    "Limit",
    "Exist",
    "Operator",
    "Result",
    "ResultColumn",
    "FromList",
    "FromTable",
    "Tuple",
    "CreateStmt",
    "ColList",
    "Field",
    "Constraints",
    "Constraint",
    "DropT",
    "DeleteStmt",
    "UpdateStmt",
    "SetList",
    "UpdateValue",
    "InsertStmt",
    "ColumnList",
    "DataList",
    "Attribute",
    "Relation",
    "Pattern",
    "IDENTIFIER",
  };
}
/* JavaCC - OriginalChecksum=0c2dcd339b2f804cf13dc60c370cfbfd (do not edit this line) */
