/* Generated By:JavaCC: Do not edit this line. SQLParserDefaultVisitor.java Version 7.0.10 */
package com.yjq.parser.jjt;

public class SQLParserDefaultVisitor implements SQLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTableName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunction node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStringLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumericLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLiteralValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSelectStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArithmeticOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogicalOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparisonOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAndExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOrExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNullExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLikeExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBetweenExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparisonExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCondition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOrderBy node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGroupBy node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLimit node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExist node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTResult node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTResultColumn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFromList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFromTable node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTuple node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCreateStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTField node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDropT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeleteStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUpdateStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSetList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUpdateValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInsertStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValueList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAttribute node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelation node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPattern node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDENTIFIER node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=02059b575023b5c2e2a542922081174e (do not edit this line) */
