/* Generated By:JavaCC: Do not edit this line. SQLParserVisitor.java Version 7.0.10 */
package com.yjq.parser.jjt;

public interface SQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTTableName node, Object data);
  public Object visit(ASTColumnName node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTNumericLiteral node, Object data);
  public Object visit(ASTLiteralValue node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTSelectStmt node, Object data);
  public Object visit(ASTArithmeticOperator node, Object data);
  public Object visit(ASTLogicalOperator node, Object data);
  public Object visit(ASTComparisonOperator node, Object data);
  public Object visit(ASTAndExpression node, Object data);
  public Object visit(ASTOrExpression node, Object data);
  public Object visit(ASTNullExpression node, Object data);
  public Object visit(ASTLikeExpression node, Object data);
  public Object visit(ASTInExpression node, Object data);
  public Object visit(ASTBetweenExpression node, Object data);
  public Object visit(ASTComparisonExpression node, Object data);
  public Object visit(ASTData node, Object data);
  public Object visit(ASTValue node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTOrderBy node, Object data);
  public Object visit(ASTGroupBy node, Object data);
  public Object visit(ASTLimit node, Object data);
  public Object visit(ASTExist node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTResult node, Object data);
  public Object visit(ASTResultColumn node, Object data);
  public Object visit(ASTFromList node, Object data);
  public Object visit(ASTFromTable node, Object data);
  public Object visit(ASTTuple node, Object data);
  public Object visit(ASTCreateStmt node, Object data);
  public Object visit(ASTColList node, Object data);
  public Object visit(ASTField node, Object data);
  public Object visit(ASTDropT node, Object data);
  public Object visit(ASTDeleteStmt node, Object data);
  public Object visit(ASTUpdateStmt node, Object data);
  public Object visit(ASTSetList node, Object data);
  public Object visit(ASTUpdateValue node, Object data);
  public Object visit(ASTInsertStmt node, Object data);
  public Object visit(ASTColumnList node, Object data);
  public Object visit(ASTDataList node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTRelation node, Object data);
  public Object visit(ASTPattern node, Object data);
  public Object visit(ASTIDENTIFIER node, Object data);
}
/* JavaCC - OriginalChecksum=ddc5ec0ae7a7d51f7e49840a546cdb83 (do not edit this line) */
