/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 7.0.10 */
package com.yjq.parser.jjt;

public interface SQLParserTreeConstants
{
  public int JJTTABLENAME = 0;
  public int JJTTABLEALIAS = 1;
  public int JJTCOLUMNNAME = 2;
  public int JJTCOLUMNALIAS = 3;
  public int JJTFUNCTION = 4;
  public int JJTSTRINGLITERAL = 5;
  public int JJTNUMERICLITERAL = 6;
  public int JJTLITERALVALUE = 7;
  public int JJTSTART = 8;
  public int JJTSTATEMENT = 9;
  public int JJTSELECTSTMT = 10;
  public int JJTARITHMETICOPERATOR = 11;
  public int JJTLOGICALOPERATOR = 12;
  public int JJTCOMPARISONOPERATOR = 13;
  public int JJTANDEXPRESSION = 14;
  public int JJTOREXPRESSION = 15;
  public int JJTNULLEXPRESSION = 16;
  public int JJTLIKEEXPRESSION = 17;
  public int JJTINEXPRESSION = 18;
  public int JJTBETWEENEXPRESSION = 19;
  public int JJTCOMPARISONEXPRESSION = 20;
  public int JJTVALUE = 21;
  public int JJTEXPRESSION = 22;
  public int JJTCONDITION = 23;
  public int JJTORDERBY = 24;
  public int JJTGROUPBY = 25;
  public int JJTLIMIT = 26;
  public int JJTEXIST = 27;
  public int JJTOPERATOR = 28;
  public int JJTRESULT = 29;
  public int JJTRESULTCOLUMN = 30;
  public int JJTFROMLIST = 31;
  public int JJTFROMTABLE = 32;
  public int JJTTUPLE = 33;
  public int JJTCRET = 34;
  public int JJTCOLLIST = 35;
  public int JJTTYPE = 36;
  public int JJTDROPT = 37;
  public int JJTDELT = 38;
  public int JJTDELLIST = 39;
  public int JJTINST = 40;
  public int JJTINLIST = 41;
  public int JJTVLIST = 42;
  public int JJTATTRIBUTE = 43;
  public int JJTRELATION = 44;
  public int JJTPATTERN = 45;
  public int JJTIDENTIFIER = 46;


  public String[] jjtNodeName = {
    "TableName",
    "TableAlias",
    "ColumnName",
    "ColumnAlias",
    "Function",
    "StringLiteral",
    "NumericLiteral",
    "LiteralValue",
    "Start",
    "Statement",
    "SelectStmt",
    "ArithmeticOperator",
    "LogicalOperator",
    "ComparisonOperator",
    "AndExpression",
    "OrExpression",
    "NullExpression",
    "LikeExpression",
    "InExpression",
    "BetweenExpression",
    "ComparisonExpression",
    "Value",
    "Expression",
    "Condition",
    "OrderBy",
    "GroupBy",
    "Limit",
    "Exist",
    "Operator",
    "Result",
    "ResultColumn",
    "FromList",
    "FromTable",
    "Tuple",
    "CreT",
    "ColList",
    "Type",
    "DropT",
    "DelT",
    "DelList",
    "InsT",
    "InList",
    "VList",
    "Attribute",
    "Relation",
    "Pattern",
    "IDENTIFIER",
  };
}
/* JavaCC - OriginalChecksum=6c12b54b89c718922ccb488e1c6346ee (do not edit this line) */
