/* SQLParser.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. SQLParser.java */
package com.yjq.parser.jjt;

import com.sun.org.apache.bcel.internal.generic.ARETURN;
import com.yjq.parser.jjt.*;
import com.yjq.parser.operator.*;
public class SQLParser/*@bgen(jjtree)*/implements SQLParserTreeConstants, SQLParserConstants {/*@bgen(jjtree)*/
  protected JJTSQLParserState jjtree = new JJTSQLParserState();public static void main(String args[]) {
        System.out.println("Reading from standard input...");
        SQLParser p = new SQLParser(System.in);
        try {
          SimpleNode n = p.Start();
          n.dump("");
//          ASTComparisonExpression comparisonExpression = p.ComparisonExpression();
//          System.out.println(comparisonExpression.compare());
          System.out.println("Thank you.");
        } catch (Exception e) {
          System.out.println("Oops.");
          System.out.println(e.getMessage());
          e.printStackTrace();
        }
    }

/* 语法解析*/
  final public ASTTableName TableName() throws ParseException {/*@bgen(jjtree) TableName */
                          ASTTableName jjtn000 = new ASTTableName(JJTTABLENAME);
                          boolean jjtc000 = true;
                          jjtree.openNodeScope(jjtn000);Token t; Token y;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        t = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
jjtn000.setName(t.image);{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        if (jj_2_1(2)) {
          t = jj_consume_token(IDENTIFIER);
jjtn000.setDbName(t.image);jjtn000.setHavaDb(true);
          jj_consume_token(DOT);
          y = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                jjtc000 = false;
jjtn000.setName(y.image);{if ("" != null) return jjtn000;}
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTColumnName ColumnName() throws ParseException {/*@bgen(jjtree) ColumnName */
                            ASTColumnName jjtn000 = new ASTColumnName(JJTCOLUMNNAME);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);Token t;Token y;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        t = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
jjtn000.setName(t.image);{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        if (jj_2_2(2)) {
          t = jj_consume_token(IDENTIFIER);
jjtn000.setTableName(t.image);jjtn000.setHaveTable(true);
          jj_consume_token(DOT);
          y = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                      jjtc000 = false;
jjtn000.setName(y.image);{if ("" != null) return jjtn000;}
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void Function() throws ParseException {/*@bgen(jjtree) Function */
  ASTFunction jjtn000 = new ASTFunction(JJTFUNCTION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IDENTIFIER);
      jj_consume_token(LEFTPARENTHESES);
      Value();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_1:
        while (true) {
          jj_consume_token(COMMA);
          Value();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[2] = jj_gen;
            break label_1;
          }
        }
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(RIGHTPARENTHESES);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ASTStringLiteral StringLiteral() throws ParseException {/*@bgen(jjtree) StringLiteral */
                                  ASTStringLiteral jjtn000 = new ASTStringLiteral(JJTSTRINGLITERAL);
                                  boolean jjtc000 = true;
                                  jjtree.openNodeScope(jjtn000);Token t;
    try {
      jj_consume_token(LQUOTATION);
      t = jj_consume_token(IDENTIFIER);
jjtn000.setValue(t.image);
      jj_consume_token(LQUOTATION);
jjtree.closeNodeScope(jjtn000, true);
                                                                          jjtc000 = false;
{if ("" != null) return jjtn000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTNumericLiteral NumericLiteral() throws ParseException {/*@bgen(jjtree) NumericLiteral */
                                    ASTNumericLiteral jjtn000 = new ASTNumericLiteral(JJTNUMERICLITERAL);
                                    boolean jjtc000 = true;
                                    jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER_LITERAL:{
        t = jj_consume_token(INTEGER_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
                            jjtc000 = false;
jjtn000.setIntegerValue(Integer.parseInt(t.image));{if ("" != null) return jjtn000;}
        break;
        }
      case FLOAT_LITERAL:{
        t = jj_consume_token(FLOAT_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
jjtn000.setDoubleValue(Double.parseDouble(t.image));{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void LiteralValue() throws ParseException {/*@bgen(jjtree) LiteralValue */
  ASTLiteralValue jjtn000 = new ASTLiteralValue(JJTLITERALVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      NumericLiteral();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public SimpleNode Start() throws ParseException {/*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Statement();
      jj_consume_token(SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void Statement() throws ParseException {/*@bgen(jjtree) Statement */
                    ASTStatement jjtn000 = new ASTStatement(JJTSTATEMENT);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);ASTSelectStmt selectStmt;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SELECT:{
        selectStmt = SelectStmt();
jjtree.closeNodeScope(jjtn000, true);
                               jjtc000 = false;
jjtn000.setType(1);jjtn000.setAstSelectStmt(selectStmt);
        break;
        }
      case CREATE:{
        CreateStmt();
        break;
        }
      case DROP:{
        DropT();
        break;
        }
      case DELETE:{
        DeleteStmt();
        break;
        }
      case INSERT:{
        InsertStmt();
        break;
        }
      case UPDATE:{
        UpdateStmt();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/**
* 查询语句
*/
  final public ASTSelectStmt SelectStmt() throws ParseException {/*@bgen(jjtree) SelectStmt */
    ASTSelectStmt jjtn000 = new ASTSelectStmt(JJTSELECTSTMT);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTResult astResult;
    ASTFromList astFromList;
    ASTExpression expression;
    try {
      jj_consume_token(SELECT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DISTINCT:{
        jj_consume_token(DISTINCT);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      astResult = Result();
jjtn000.setAstResult(astResult);
      jj_consume_token(FROM);
      astFromList = FromList();
jjtn000.setAstFromList(astFromList);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WHERE:
      case NOT:
      case EXISTS:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHERE:{
          jj_consume_token(WHERE);
          expression = Expression();
jjtn000.setExpression(expression);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          if (jj_2_3(2)) {
            Exist();
          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GROUP:{
        GroupBy();
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ORDER:{
        OrderBy();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LIMIT:{
        Limit();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void ArithmeticOperator() throws ParseException {/*@bgen(jjtree) ArithmeticOperator */
  ASTArithmeticOperator jjtn000 = new ASTArithmeticOperator(JJTARITHMETICOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        break;
        }
      case PLUS:{
        jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        break;
        }
      case TIMES:{
        jj_consume_token(TIMES);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void LogicalOperator() throws ParseException {/*@bgen(jjtree) LogicalOperator */
  ASTLogicalOperator jjtn000 = new ASTLogicalOperator(JJTLOGICALOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        jj_consume_token(OR);
        break;
        }
      case AND:{
        jj_consume_token(AND);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void ComparisonOperator() throws ParseException {/*@bgen(jjtree) ComparisonOperator */
  ASTComparisonOperator jjtn000 = new ASTComparisonOperator(JJTCOMPARISONOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
        break;
        }
      case LESSTHAN:{
        jj_consume_token(LESSTHAN);
        break;
        }
      case LESSTHANOREQUALTO:{
        jj_consume_token(LESSTHANOREQUALTO);
        break;
        }
      case GREATERTHAN:{
        jj_consume_token(GREATERTHAN);
        break;
        }
      case GREATERTHANOREQUALTO:{
        jj_consume_token(GREATERTHANOREQUALTO);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/**
* 逻辑-and表达�?
*/
  final public ASTAndExpression AndExpression() throws ParseException {/*@bgen(jjtree) AndExpression */
                                  ASTAndExpression jjtn000 = new ASTAndExpression(JJTANDEXPRESSION);
                                  boolean jjtc000 = true;
                                  jjtree.openNodeScope(jjtn000);ASTCondition condition;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
jjtn000.setLeftNot(true);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      condition = Condition();
jjtn000.setLeft(condition);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        jj_consume_token(AND);
jjtn000.setAnd(true);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NOT:{
          jj_consume_token(NOT);
jjtn000.setRightNot(true);
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          ;
        }
        condition = Condition();
jjtn000.setRight(condition);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                             jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* 逻辑-or表达�?
*/
  final public ASTOrExpression OrExpression() throws ParseException {/*@bgen(jjtree) OrExpression */
                                ASTOrExpression jjtn000 = new ASTOrExpression(JJTOREXPRESSION);
                                boolean jjtc000 = true;
                                jjtree.openNodeScope(jjtn000);ASTAndExpression astAndExpression;
    try {
      astAndExpression = AndExpression();
jjtn000.setLeft(astAndExpression);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        jj_consume_token(OR);
jjtn000.setOr(true);
        astAndExpression = AndExpression();
jjtn000.setRight(astAndExpression);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                          jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* 空�?�表达式
*/
  final public ASTNullExpression NullExpression() throws ParseException {/*@bgen(jjtree) NullExpression */
  ASTNullExpression jjtn000 = new ASTNullExpression(JJTNULLEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ColumnName();
        jj_consume_token(ISNULL);
        break;
        }
      case IS:{
        jj_consume_token(IS);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NOT:{
          jj_consume_token(NOT);
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          ;
        }
        jj_consume_token(NULL);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* like匹配表达�?
*/
  final public ASTLikeExpression LikeExpression() throws ParseException {/*@bgen(jjtree) LikeExpression */
  ASTLikeExpression jjtn000 = new ASTLikeExpression(JJTLIKEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      ColumnName();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        ;
      }
      jj_consume_token(LIKE);
      StringLiteral();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* in判断表达�?
*/
  final public ASTInExpression InExpression() throws ParseException {/*@bgen(jjtree) InExpression */
  ASTInExpression jjtn000 = new ASTInExpression(JJTINEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      ColumnName();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      jj_consume_token(IN);
      jj_consume_token(LEFTPARENTHESES);
      Value();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_2:
        while (true) {
          jj_consume_token(COMMA);
          Value();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[23] = jj_gen;
            break label_2;
          }
        }
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        ;
      }
      jj_consume_token(RIGHTPARENTHESES);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* between表达�?
*/
  final public ASTBetweenExpression BetweenExpression() throws ParseException {/*@bgen(jjtree) BetweenExpression */
  ASTBetweenExpression jjtn000 = new ASTBetweenExpression(JJTBETWEENEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      ColumnName();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        ;
      }
      jj_consume_token(BETWEEN);
      Value();
      jj_consume_token(AND);
      Value();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* 比较表达�?
*/
  final public ASTComparisonExpression ComparisonExpression() throws ParseException {/*@bgen(jjtree) ComparisonExpression */
    ASTComparisonExpression jjtn000 = new ASTComparisonExpression(JJTCOMPARISONEXPRESSION);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTColumnName columnName;
    ASTValue value;
    try {
      columnName = ColumnName();
jjtn000.setColumnName(columnName);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
jjtn000.setOperator(new Equal());
        break;
        }
      case LESSTHAN:{
        jj_consume_token(LESSTHAN);
jjtn000.setOperator(new LessThan());
        break;
        }
      case LESSTHANOREQUALTO:{
        jj_consume_token(LESSTHANOREQUALTO);
jjtn000.setOperator(new LessThanOrEqualTo());
        break;
        }
      case GREATERTHAN:{
        jj_consume_token(GREATERTHAN);
jjtn000.setOperator(new GreaterThan());
        break;
        }
      case GREATERTHANOREQUALTO:{
        jj_consume_token(GREATERTHANOREQUALTO);
jjtn000.setOperator(new GreaterThanOrEqualTo());
        break;
        }
      case NOTEQUAL:{
        jj_consume_token(NOTEQUAL);
jjtn000.setOperator(new NotEqual());
        break;
        }
      case NOTGREATER:{
        jj_consume_token(NOTGREATER);
jjtn000.setOperator(new LessThanOrEqualTo());
        break;
        }
      case NOTLESS:{
        jj_consume_token(NOTLESS);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtn000.setOperator(new GreaterThanOrEqualTo());
      value = Value();
jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
jjtn000.setValue(value);{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTData Data() throws ParseException {/*@bgen(jjtree) Data */
                ASTData jjtn000 = new ASTData(JJTDATA);
                boolean jjtc000 = true;
                jjtree.openNodeScope(jjtn000);ASTNumericLiteral numericLiteral;ASTStringLiteral stringLiteral;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER_LITERAL:
      case FLOAT_LITERAL:{
        numericLiteral = NumericLiteral();
jjtree.closeNodeScope(jjtn000, true);
                                       jjtc000 = false;
jjtn000.setNumericLiteral(numericLiteral); {if ("" != null) return jjtn000;}
        break;
        }
      case LQUOTATION:{
        stringLiteral = StringLiteral();
jjtree.closeNodeScope(jjtn000, true);
                                       jjtc000 = false;
jjtn000.setStringLiteral(stringLiteral); {if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTValue Value() throws ParseException {/*@bgen(jjtree) Value */
    ASTValue jjtn000 = new ASTValue(JJTVALUE);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTData data;
    ASTColumnName columnName;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LQUOTATION:
      case INTEGER_LITERAL:
      case FLOAT_LITERAL:{
        data = Data();
jjtree.closeNodeScope(jjtn000, true);
                   jjtc000 = false;
jjtn000.setData(data);
        break;
        }
      case IDENTIFIER:{
        columnName = ColumnName();
jjtree.closeNodeScope(jjtn000, true);
                                 jjtc000 = false;
jjtn000.setColumnName(columnName);{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTExpression Expression() throws ParseException {/*@bgen(jjtree) Expression */
                            ASTExpression jjtn000 = new ASTExpression(JJTEXPRESSION);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);ASTOrExpression expression;
    try {
      expression = OrExpression();
jjtree.closeNodeScope(jjtn000, true);
                                 jjtc000 = false;
jjtn000.setOrExpression(expression);{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* where条件
*/
  final public ASTCondition Condition() throws ParseException {/*@bgen(jjtree) Condition */
    ASTCondition jjtn000 = new ASTCondition(JJTCONDITION);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTComparisonExpression comparisonExpression;
    ASTInExpression inExpression;
    ASTBetweenExpression betweenExpression;
    ASTLikeExpression likeExpression;
    ASTNullExpression nullExpression;
    try {
      if (jj_2_4(2)) {
        comparisonExpression = ComparisonExpression();
jjtree.closeNodeScope(jjtn000, true);
                                                               jjtc000 = false;
jjtn000.setExpression(comparisonExpression);{if ("" != null) return jjtn000;}
      } else if (jj_2_5(2)) {
        inExpression = InExpression();
jjtree.closeNodeScope(jjtn000, true);
                                                 jjtc000 = false;
jjtn000.setExpression(inExpression);{if ("" != null) return jjtn000;}
      } else if (jj_2_6(2)) {
        betweenExpression = BetweenExpression();
jjtree.closeNodeScope(jjtn000, true);
                                                           jjtc000 = false;
jjtn000.setExpression(betweenExpression);{if ("" != null) return jjtn000;}
      } else if (jj_2_7(2)) {
        likeExpression = LikeExpression();
jjtree.closeNodeScope(jjtn000, true);
                                                     jjtc000 = false;
jjtn000.setExpression(likeExpression);{if ("" != null) return jjtn000;}
      } else if (jj_2_8(2)) {
        nullExpression = NullExpression();
jjtree.closeNodeScope(jjtn000, true);
                                                     jjtc000 = false;
jjtn000.setExpression(nullExpression);{if ("" != null) return jjtn000;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/**
* ORDER BY子句
*/
  final public void OrderBy() throws ParseException {/*@bgen(jjtree) OrderBy */
  ASTOrderBy jjtn000 = new ASTOrderBy(JJTORDERBY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ORDER);
      jj_consume_token(BY);
      ColumnName();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_3:
        while (true) {
          jj_consume_token(COMMA);
          ColumnName();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[29] = jj_gen;
            break label_3;
          }
        }
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASC:
      case DESC:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASC:{
          jj_consume_token(ASC);
          break;
          }
        case DESC:{
          jj_consume_token(DESC);
          break;
          }
        default:
          jj_la1[31] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:{
        jj_consume_token(NULL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FIRST:{
          jj_consume_token(FIRST);
          break;
          }
        case LAST:{
          jj_consume_token(LAST);
          break;
          }
        default:
          jj_la1[33] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/**
* GROUP BY 子句
*/
  final public void GroupBy() throws ParseException {/*@bgen(jjtree) GroupBy */
  ASTGroupBy jjtn000 = new ASTGroupBy(JJTGROUPBY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(GROUP);
      jj_consume_token(BY);
      ColumnName();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_4:
        while (true) {
          jj_consume_token(COMMA);
          ColumnName();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[35] = jj_gen;
            break label_4;
          }
        }
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case HAVING:{
        jj_consume_token(HAVING);
        Expression();
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/**
* LIMIT子句
*/
  final public void Limit() throws ParseException {/*@bgen(jjtree) Limit */
  ASTLimit jjtn000 = new ASTLimit(JJTLIMIT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LIMIT);
      jj_consume_token(INTEGER_LITERAL);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OFFSET:
      case COMMA:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OFFSET:{
          jj_consume_token(OFFSET);
          jj_consume_token(INTEGER_LITERAL);
          break;
          }
        case COMMA:{
          jj_consume_token(COMMA);
          jj_consume_token(INTEGER_LITERAL);
          break;
          }
        default:
          jj_la1[38] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        ;
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/**
* Exist
*/
  final public void Exist() throws ParseException {/*@bgen(jjtree) Exist */
  ASTExist jjtn000 = new ASTExist(JJTEXIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      jj_consume_token(EXISTS);
      jj_consume_token(LEFTPARENTHESES);
      SelectStmt();
      jj_consume_token(RIGHTPARENTHESES);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void Operator() throws ParseException {/*@bgen(jjtree) Operator */
  ASTOperator jjtn000 = new ASTOperator(JJTOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case TIMES:
      case DIVIDE:{
        ArithmeticOperator();
        break;
        }
      case AND:
      case OR:{
        LogicalOperator();
        break;
        }
      case EQUAL:
      case GREATERTHAN:
      case GREATERTHANOREQUALTO:
      case LESSTHAN:
      case LESSTHANOREQUALTO:{
        ComparisonOperator();
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ASTResult Result() throws ParseException {/*@bgen(jjtree) Result */
    ASTResult jjtn000 = new ASTResult(JJTRESULT);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTResultColumn astResultColumn;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        jj_consume_token(TIMES);
jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
jjtn000.setAll(true);{if ("" != null) return jjtn000;}
        break;
        }
      case IDENTIFIER:{
        astResultColumn = ResultColumn();
jjtn000.getResultColumns().add(astResultColumn);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          label_5:
          while (true) {
            jj_consume_token(COMMA);
            astResultColumn = ResultColumn();
jjtn000.getResultColumns().add(astResultColumn);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[42] = jj_gen;
              break label_5;
            }
          }
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          ;
        }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                    jjtc000 = false;
{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[44] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTResultColumn ResultColumn() throws ParseException {/*@bgen(jjtree) ResultColumn */
    ASTResultColumn jjtn000 = new ASTResultColumn(JJTRESULTCOLUMN);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);ASTTableName tableName;
    ASTColumnName columnName;
    ASTFunction function;
    Token t;
    try {
      if (jj_2_9(4)) {
        tableName = TableName();
        jj_consume_token(DOT);
        jj_consume_token(TIMES);
jjtree.closeNodeScope(jjtn000, true);
                                                     jjtc000 = false;
jjtn000.setTableName(tableName);jjtn000.setType(1);{if ("" != null) return jjtn000;}
      } else if (jj_2_10(4)) {
        columnName = ColumnName();
jjtn000.setColumnName(columnName);jjtn000.setType(2);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AS:{
          jj_consume_token(AS);
          t = jj_consume_token(IDENTIFIER);
jjtn000.setHaveAlias(Boolean.TRUE);jjtn000.setAlias(t.image);
          break;
          }
        default:
          jj_la1[45] = jj_gen;
          ;
        }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                                                                                           jjtc000 = false;
{if ("" != null) return jjtn000;}
      } else if (jj_2_11(2)) {
        Function();
jjtree.closeNodeScope(jjtn000, true);
                              jjtc000 = false;
jjtn000.setType(3);{if ("" != null) return jjtn000;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

//void Expr():{}
//{
//    LOOKAHEAD(2)ColumnName() Exprr()
//    | LOOKAHEAD(2)LiteralValue() Exprr()
//    | LOOKAHEAD(2)TableName()<DOT>ColumnName() Exprr()
//    | LOOKAHEAD(2)Function()
//    | LOOKAHEAD(2)<LEFTPARENTHESES> Expr()[(<COMMA>Expr())+]<RIGHTPARENTHESES> Exprr()
//}
//void Exprr():{}
//{
//    [Operator() Expr() Exprr()
//    | LOOKAHEAD(2)[<NOT>] <IN> <LEFTPARENTHESES> [SelectStmt() | Expr()[(<COMMA>Expr())+]]<RIGHTPARENTHESES>/* IN语句*/Exprr()
//    | LOOKAHEAD(2)[<NOT>] <BETWEEN> Expr() <AND> Expr() /* between */Exprr()
//    | LOOKAHEAD(2)(<NOTNULL> | <ISNULL> | <NOT> <NULL> )Exprr()
//    | LOOKAHEAD(2)[<NOT>] <LIKE> Expr() /* LIKE语句 */Exprr()]
//}
//void Exprrtemp():{}
//{
//    ColumnName()
//    | LiteralValue()
//    | TableName()<DOT>ColumnName()
//    | FunctionName()<LEFTPARENTHESES> [Expr()[(<COMMA>Expr())+]] |[<COMMA>] <RIGHTPARENTHESES>
//    | Expr() Operator() Expr()
//    | <LEFTPARENTHESES> Expr()[(<COMMA>Expr())+]<RIGHTPARENTHESES>
//    | Expr() [<NOT>] <IN> <LEFTPARENTHESES> [SelectStmt() | Expr()[(<COMMA>Expr())+]]<RIGHTPARENTHESES>/* IN语句*/
//    | Expr() [<NOT>] <BETWEEN> Expr() <AND> Expr() /* between */
//    | Expr() (<NOTNULL> | <ISNULL> | <NOT> <NULL> )
//    | Expr() [<NOT>] <LIKE> Expr() /* LIKE语句 */
//}
  final public ASTFromList FromList() throws ParseException {/*@bgen(jjtree) FromList */
                        ASTFromList jjtn000 = new ASTFromList(JJTFROMLIST);
                        boolean jjtc000 = true;
                        jjtree.openNodeScope(jjtn000);ASTFromTable fromTable;
    try {
      fromTable = FromTable();
jjtn000.getFromTables().add(fromTable);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_6:
        while (true) {
          jj_consume_token(COMMA);
          fromTable = FromTable();
jjtn000.getFromTables().add(fromTable);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[46] = jj_gen;
            break label_6;
          }
        }
        break;
        }
      default:
        jj_la1[47] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                                                  jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTFromTable FromTable() throws ParseException {/*@bgen(jjtree) FromTable */
                          ASTFromTable jjtn000 = new ASTFromTable(JJTFROMTABLE);
                          boolean jjtc000 = true;
                          jjtree.openNodeScope(jjtn000);ASTTableName tableName;Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        tableName = TableName();
jjtn000.setTableName(tableName);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AS:
        case IDENTIFIER:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case AS:{
            jj_consume_token(AS);
            break;
            }
          default:
            jj_la1[48] = jj_gen;
            ;
          }
          t = jj_consume_token(IDENTIFIER);
jjtn000.setHavaAlias(true);jjtn000.setAlias(t.image);
          break;
          }
        default:
          jj_la1[49] = jj_gen;
          ;
        }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                                                jjtc000 = false;
{if ("" != null) return jjtn000;}
        break;
        }
      default:
        jj_la1[50] = jj_gen;
        if (jj_2_12(2)) {
          jj_consume_token(LEFTPARENTHESES);
          SelectStmt();
          jj_consume_token(RIGHTPARENTHESES);
jjtree.closeNodeScope(jjtn000, true);
                                                                     jjtc000 = false;
{if ("" != null) return jjtn000;}
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

//void Condition():{}
//{
//    /*[Condition()<AND>Condition()]|*/
//    /*[Tuple()<IN>Query()]*/
//    Expr()
//    | Expr() <IS> <NULL>
//    | Expr() <NOTNULL>
//    | Expr() <ISNULL>
//}
  final public void Tuple() throws ParseException {/*@bgen(jjtree) Tuple */
  ASTTuple jjtn000 = new ASTTuple(JJTTUPLE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Attribute();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*--------- Create 语句 ----------*/
  final public ASTCreateStmt CreateStmt() throws ParseException {/*@bgen(jjtree) CreateStmt */
                            ASTCreateStmt jjtn000 = new ASTCreateStmt(JJTCREATESTMT);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);Token t;ASTColList colList;
    try {
      jj_consume_token(CREATE);
      jj_consume_token(TABLE);
      t = jj_consume_token(IDENTIFIER);
jjtn000.setTableName(t.image);
      jj_consume_token(LEFTPARENTHESES);
      colList = ColList();
jjtn000.setColList(colList);
      jj_consume_token(RIGHTPARENTHESES);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTColList ColList() throws ParseException {/*@bgen(jjtree) ColList */
                      ASTColList jjtn000 = new ASTColList(JJTCOLLIST);
                      boolean jjtc000 = true;
                      jjtree.openNodeScope(jjtn000);ASTField field;
    try {
      field = Field();
jjtn000.getFields().add(field);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_7:
        while (true) {
          jj_consume_token(COMMA);
          field = Field();
jjtn000.getFields().add(field);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[51] = jj_gen;
            break label_7;
          }
        }
        break;
        }
      default:
        jj_la1[52] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                  jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTField Field() throws ParseException {/*@bgen(jjtree) Field */
                  ASTField jjtn000 = new ASTField(JJTFIELD);
                  boolean jjtc000 = true;
                  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDENTIFIER);
jjtn000.setName(t.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        t = jj_consume_token(INT);
        break;
        }
      case DATE:{
        t = jj_consume_token(DATE);
        break;
        }
      case DOUBLE:{
        t = jj_consume_token(DOUBLE);
        break;
        }
      case CHAR:{
        t = jj_consume_token(CHAR);
        jj_consume_token(LEFTPARENTHESES);
        jj_consume_token(INTEGER_LITERAL);
        jj_consume_token(RIGHTPARENTHESES);
        break;
        }
      default:
        jj_la1[53] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.setDataType(t.image);{if ("" != null) return jjtn000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*--------- DELETE & DROP 语句 ----------*/
  final public void DropT() throws ParseException {/*@bgen(jjtree) DropT */
  ASTDropT jjtn000 = new ASTDropT(JJTDROPT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DROP);
      jj_consume_token(TABLE);
      Relation();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ASTDeleteStmt DeleteStmt() throws ParseException {/*@bgen(jjtree) DeleteStmt */
                            ASTDeleteStmt jjtn000 = new ASTDeleteStmt(JJTDELETESTMT);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);ASTTableName tableName; ASTExpression expression;
    try {
      jj_consume_token(DELETE);
      jj_consume_token(FROM);
      tableName = TableName();
jjtn000.setTableName(tableName);
      jj_consume_token(WHERE);
      expression = Expression();
jjtree.closeNodeScope(jjtn000, true);
                                                                                                             jjtc000 = false;
jjtn000.setExpression(expression);{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*-------- UPDATE 语句 -----------*/
  final public ASTUpdateStmt UpdateStmt() throws ParseException {/*@bgen(jjtree) UpdateStmt */
                            ASTUpdateStmt jjtn000 = new ASTUpdateStmt(JJTUPDATESTMT);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);ASTTableName tableName;ASTSetList setList; ASTExpression expression;
    try {
      jj_consume_token(UPDATE);
      tableName = TableName();
jjtn000.setTableName(tableName);
      jj_consume_token(SET);
      setList = SetList();
jjtn000.setSetList(setList);
      jj_consume_token(WHERE);
      expression = Expression();
jjtree.closeNodeScope(jjtn000, true);
                                       jjtc000 = false;
jjtn000.setExpression(expression);{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTSetList SetList() throws ParseException {/*@bgen(jjtree) SetList */
                      ASTSetList jjtn000 = new ASTSetList(JJTSETLIST);
                      boolean jjtc000 = true;
                      jjtree.openNodeScope(jjtn000);ASTUpdateValue updateValue;
    try {
      updateValue = UpdateValue();
jjtn000.getUpdateValues().add(updateValue);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_8:
        while (true) {
          jj_consume_token(COMMA);
          updateValue = UpdateValue();
jjtn000.getUpdateValues().add(updateValue);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[54] = jj_gen;
            break label_8;
          }
        }
        break;
        }
      default:
        jj_la1[55] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                                                                    jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ASTUpdateValue UpdateValue() throws ParseException {/*@bgen(jjtree) UpdateValue */
                              ASTUpdateValue jjtn000 = new ASTUpdateValue(JJTUPDATEVALUE);
                              boolean jjtc000 = true;
                              jjtree.openNodeScope(jjtn000);ASTColumnName columnName;ASTValue value;
    try {
      columnName = ColumnName();
jjtn000.setColumnName(columnName);
      jj_consume_token(EQUAL);
      value = Value();
jjtree.closeNodeScope(jjtn000, true);
                                                                                           jjtc000 = false;
jjtn000.setValue(value); {if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*-------- INSERT 语句 -----------*/
  final public void InsertStmt() throws ParseException {/*@bgen(jjtree) InsertStmt */
                   ASTInsertStmt jjtn000 = new ASTInsertStmt(JJTINSERTSTMT);
                   boolean jjtc000 = true;
                   jjtree.openNodeScope(jjtn000);ASTTableName tableName; ASTColumnList columnList; ASTValueList valueList;
    try {
      jj_consume_token(INSERT);
      jj_consume_token(INTO);
      tableName = TableName();
jjtn000.setTableName(tableName);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEFTPARENTHESES:{
        jj_consume_token(LEFTPARENTHESES);
        columnList = ColumnList();
jjtn000.setColumnList(columnList);
        jj_consume_token(RIGHTPARENTHESES);
        break;
        }
      default:
        jj_la1[56] = jj_gen;
        ;
      }
      jj_consume_token(VALUES);
      jj_consume_token(LEFTPARENTHESES);
      valueList = DataList();
jjtn000.setValueList(valueList);
      jj_consume_token(RIGHTPARENTHESES);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ASTColumnList ColumnList() throws ParseException {/*@bgen(jjtree) ColumnList */
                            ASTColumnList jjtn000 = new ASTColumnList(JJTCOLUMNLIST);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);ASTColumnName columnName;
    try {
      columnName = ColumnName();
jjtn000.getColumnNames().add(columnName);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_9:
        while (true) {
          jj_consume_token(COMMA);
          columnName = ColumnName();
jjtn000.getColumnNames().add(columnName);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[57] = jj_gen;
            break label_9;
          }
        }
        break;
        }
      default:
        jj_la1[58] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void DataList() throws ParseException {/*@bgen(jjtree) DataList */
                 ASTDataList jjtn000 = new ASTDataList(JJTDATALIST);
                 boolean jjtc000 = true;
                 jjtree.openNodeScope(jjtn000);ASTData data;
    try {
      data = Data();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        label_10:
        while (true) {
          jj_consume_token(COMMA);
          data = Data();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[59] = jj_gen;
            break label_10;
          }
        }
        break;
        }
      default:
        jj_la1[60] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*-------------------*/
  final public void Attribute() throws ParseException {/*@bgen(jjtree) Attribute */
  ASTAttribute jjtn000 = new ASTAttribute(JJTATTRIBUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      IDENTIFIER();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void Relation() throws ParseException {/*@bgen(jjtree) Relation */
  ASTRelation jjtn000 = new ASTRelation(JJTRELATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      IDENTIFIER();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void Pattern() throws ParseException {/*@bgen(jjtree) Pattern */
  ASTPattern jjtn000 = new ASTPattern(JJTPATTERN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LQUOTATION);
      IDENTIFIER();
      jj_consume_token(LQUOTATION);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*-------------------*/
  final public void IDENTIFIER() throws ParseException {/*@bgen(jjtree) IDENTIFIER */
  ASTIDENTIFIER jjtn000 = new ASTIDENTIFIER(JJTIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IDENTIFIER);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_3R_InExpression_225_5_13()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    if (jj_scan_token(IN)) return true;
    return false;
  }

  private boolean jj_3R_Exist_318_5_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    if (jj_scan_token(EXISTS)) return true;
    if (jj_scan_token(LEFTPARENTHESES)) return true;
    return false;
  }

  private boolean jj_3R_Function_126_5_20()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LEFTPARENTHESES)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_LikeExpression_217_5_15()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    if (jj_scan_token(LIKE)) return true;
    return false;
  }

  private boolean jj_3R_ColumnName_121_5_32()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_ColumnName_121_5_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ColumnName_121_5_32()) {
    jj_scanpos = xsp;
    if (jj_3_2()) return true;
    }
    return false;
  }

  private boolean jj_3R_NullExpression_211_7_30()
 {
    if (jj_scan_token(IS)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_TableName_116_5_31()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_TableName_116_5_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_TableName_116_5_31()) {
    jj_scanpos = xsp;
    if (jj_3_1()) return true;
    }
    return false;
  }

  private boolean jj_3R_NullExpression_209_5_29()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    if (jj_scan_token(ISNULL)) return true;
    return false;
  }

  private boolean jj_3R_NullExpression_209_5_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_NullExpression_209_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_NullExpression_211_7_30()) return true;
    }
    return false;
  }

  private boolean jj_3R_SelectStmt_161_5_21()
 {
    if (jj_scan_token(SELECT)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_252_7_28()
 {
    if (jj_scan_token(NOTGREATER)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_251_7_27()
 {
    if (jj_scan_token(NOTEQUAL)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_250_7_26()
 {
    if (jj_scan_token(GREATERTHANOREQUALTO)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_249_7_25()
 {
    if (jj_scan_token(GREATERTHAN)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_248_7_24()
 {
    if (jj_scan_token(LESSTHANOREQUALTO)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_3R_Function_126_5_20()) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_247_7_23()
 {
    if (jj_scan_token(LESSTHAN)) return true;
    return false;
  }

  private boolean jj_3R_ResultColumn_341_101_19()
 {
    if (jj_scan_token(AS)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ResultColumn_341_101_19()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_246_6_22()
 {
    if (jj_scan_token(EQUAL)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_3R_TableName_116_5_17()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(TIMES)) return true;
    return false;
  }

  private boolean jj_3R_ComparisonExpression_245_5_12()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ComparisonExpression_246_6_22()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_247_7_23()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_248_7_24()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_249_7_25()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_250_7_26()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_251_7_27()) {
    jj_scanpos = xsp;
    if (jj_3R_ComparisonExpression_252_7_28()) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_NullExpression_209_5_16()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_LikeExpression_217_5_15()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_BetweenExpression_233_5_14()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_InExpression_225_5_13()) return true;
    return false;
  }

  private boolean jj_3_12()
 {
    if (jj_scan_token(LEFTPARENTHESES)) return true;
    if (jj_3R_SelectStmt_161_5_21()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_ComparisonExpression_245_5_12()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_Exist_318_5_11()) return true;
    return false;
  }

  private boolean jj_3R_BetweenExpression_233_5_14()
 {
    if (jj_3R_ColumnName_121_5_18()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    if (jj_scan_token(BETWEEN)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public SQLParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[61];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0xfa0,0x10000,0x1000,0x40001000,0x0,0x80000,0x0,0x0,0x800000,0x0,0x40000000,0x40000000,0x800000,0x0,0x40000000,0x20000000,0x40000000,0x40000000,0x0,0x0,0x40000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40000000,0x800000,0x0,0x0,0x0,0x200000,0x0,0x0,0x200000,0x200000,0x0,0x0,0x0,0x1e000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x8000,0x8000,0x0,0x0,0x0,0x0,0x2000,0x10,0x0,0x40,0x1e00000,0x4,0x3c100000,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x8000,0x8000,0x0,0x3c100000,0x0,0x0,0x8000,0x8000,0x300,0x300,0xc00,0x2,0x8000,0x8000,0x20,0x8080,0x8080,0x0,0x3df00004,0x8000,0x8000,0x800000,0x0,0x8000,0x8000,0x0,0x0,0x0,0x8000,0x8000,0x0,0x8000,0x8000,0x40000,0x8000,0x8000,0x8000,0x8000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x80,0x80,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x7,0x38,0xb8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x80,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[12];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SQLParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SQLParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new SQLParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SQLParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new SQLParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new SQLParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SQLParser(SQLParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SQLParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 61; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[73];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 61; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 73; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 12; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

     }
